name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:

  lint-test-build-android-linux-web:
    name: Lint & Test & Build - Android, Linux, Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 14
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: ubuntu-flutter
      - name: Lint
        run: flutter analyze
      - name: Test
        run: flutter test
      - name: Build for Android
        run: flutter build apk
      - name: Build for Linux
        run: flutter build linux
      - name: Build for Web
        run: flutter build web

  build-ios-macos:
    name: Build - iOS & MacOS
    runs-on: macos-latest
    needs: [lint-test-build-android-linux-web]
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: macos-flutter
      - name: Build for iOS
        run: flutter build ios --release --no-codesign
      - name: Build for MacOS
        run: flutter build macos

  build-windows:
    name: Build - Windows
    runs-on: windows-latest
    needs: [lint-test-build-android-linux-web]
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: windows-flutter
      - name: Build for iOS
        run: flutter build windows